export const GET_POLICIES = 'GET_POLICIES';
export const SET_POLICIES = 'SET_POLICIES';
export const SET_SECTORS = 'SET_SECTORS';
export const UPDATE_METADATA = 'UPDATE_METADATA';
export const SET_STATUS = 'SET_STATUS';